### PR TITLE
Feature/invoke wiki method

### PR DESCRIPTION
**Pull request by lipkau**
# New Invoke Method
Implementation of a centralized method to make the REST calls.

This allows for only one implementation of error handling, credential management and code reduction

### CODE REVIEW

**Comment by brianbunke** [comment]
This is so awesome 😁

Mind if I merge it into a "1.1" version branch, instead of straight to master? Lets you submit another PR without building, and then it can drop a finalized `1.1` release when I merge it into `master`.

**Comment by lipkau** [comment]
Absolutely

**Comment by brianbunke** [comment]
And just to profess my love on a public medium: ❤️ for updating the test suite to work with Pester 4.

**Comment by brianbunke** [comment]
Just for future reference: I merged this PR into `1.1`, but we then decided to split it off into a `develop` branch instead. @lipkau may make breaking changes with some upcoming PRs that would make more sense to call `2.0` instead of `1.1`.

**Pull request merged**
